//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Vouchers = new HashSet<Vouchers>();
        }
    
        public int ID_Game { get; set; }
        public string GameName { get; set; }
        public int Coast { get; set; }
        public int genre_ID { get; set; }
        public int publisher_ID { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual SysRequirements SysRequirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vouchers> Vouchers { get; set; }
    }
}
