//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRequirements
    {
        public int GameID { get; set; }
        public string Processor { get; set; }
        public string VideoCard { get; set; }
        public int DDR { get; set; }
        public int DiskSpace { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
