//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public int ID_Voucher { get; set; }
        public int game_id { get; set; }
        public int orders_id { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
